/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validates frontmatter for all chapter MDX files in Physical AI & Humanoid Robotics textbook
 */
export interface ChapterMetadataSchema {
  /**
   * Chapter title (H1 equivalent)
   */
  title: string;
  /**
   * Brief chapter summary for SEO
   */
  description: string;
  /**
   * Numeric ordering in sidebar navigation
   */
  sidebar_position: number;
  /**
   * SEO keywords for search optimization
   *
   * @minItems 5
   * @maxItems 15
   */
  keywords:
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
  /**
   * Parent module identifier
   */
  module: "module-0" | "module-1" | "module-2" | "module-3" | "module-4" | "capstone";
  /**
   * Specific week assignment (e.g., 'Week 4 – Tuesday & Thursday')
   */
  week_mapping: string;
  /**
   * Required prior knowledge (internal chapters + external topics)
   *
   * @minItems 0
   */
  prerequisites: {
    type: "internal" | "external";
    title: string;
    /**
     * Required for internal prerequisites
     */
    link?: string;
    /**
     * Optional context for prerequisite
     */
    description?: string;
    [k: string]: unknown;
  }[];
  /**
   * Chapter-specific learning objectives (active voice verbs)
   *
   * @minItems 3
   * @maxItems 7
   */
  learning_objectives:
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string];
  /**
   * Primary exercise category for this chapter
   */
  assessment_type: "conceptual" | "computational" | "implementation";
  /**
   * Target reader skill level
   */
  difficulty_level: "beginner" | "intermediate" | "advanced";
  /**
   * How this chapter integrates with capstone project (optional)
   */
  capstone_component?: string;
  /**
   * All code dependencies with exact version pinning
   */
  code_dependencies: string[];
  /**
   * Estimated study hours for chapter completion
   */
  estimated_time: number;
  /**
   * Optional Docusaurus tags for categorization
   */
  tags?: string[];
}
