/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validates glossary term definitions for FlexSearch indexing
 */
export interface GlossaryEntrySchema {
  /**
   * Canonical term (unique identifier)
   */
  term: string;
  /**
   * Clear, concise definition of the term
   */
  definition: string;
  /**
   * Associated concepts (must exist in glossary)
   */
  relatedTerms?: string[];
  /**
   * Chapters referencing this term
   *
   * @minItems 1
   */
  chapters: [string, ...string[]];
  /**
   * Alternative names for the term
   */
  aliases?: string[];
  /**
   * Term classification for organization
   */
  category?:
    | "robotics"
    | "ai"
    | "mathematics"
    | "physics"
    | "control-theory"
    | "computer-vision"
    | "nlp"
    | "hardware"
    | "software"
    | "simulation";
  /**
   * LaTeX representation if mathematical symbol (e.g., '\\theta' for theta)
   */
  latex?: string;
}
