/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validates frontmatter for module overview pages
 */
export interface ModuleMetadataSchema {
  /**
   * Full module name
   */
  title: string;
  /**
   * Module overview (2-3 sentences)
   */
  description: string;
  /**
   * Module order in navigation
   */
  sidebar_position: number;
  /**
   * Unique module identifier
   */
  module_id: "module-0" | "module-1" | "module-2" | "module-3" | "module-4" | "capstone";
  /**
   * Week span in 13-week course (e.g., 'Week 13' or 'Weeks 3-5')
   */
  week_range: string;
  /**
   * High-level module objectives (active voice)
   *
   * @minItems 3
   * @maxItems 7
   */
  learning_outcomes:
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string];
  /**
   * How module contributes to capstone project
   */
  capstone_integration?: string;
  /**
   * Total study hours for entire module
   */
  estimated_time: number;
  /**
   * SEO keywords for module
   *
   * @minItems 5
   * @maxItems 15
   */
  keywords?:
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
}
